#!/bin/bash

set -e

verbose() {
	! test -z "$VERBOSE"
}

verbose && echo "Measuring line lengths..."
tools/measure

# SITE_DIR is the final location where we want generated content to be
SITE_DIR="./public"

# GENERATE_DIR is where the content will be generated initially
GENERATE_DIR="$(mktemp -d)"

function cleanup() {
  rm -rf "$GENERATE_DIR"
}
trap cleanup EXIT

echo "Generating HTML to $GENERATE_DIR..."
go run tools/generate.go $GENERATE_DIR

echo "Copying $GENERATE_DIR to $SITE_DIR"
cp -rf "${GENERATE_DIR}/." "$SITE_DIR"
